// SEARCH
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';

// PHOTOS
export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
