// SEARCH
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';

// PHOTOS
export const FETCH_RANDOM_PHOTOS_START = 'FETCH_RANDOM_PHOTOS_START';
export const FETCH_RANDOM_PHOTOS_SUCCESS = 'FETCH_RANDOM_PHOTOS_SUCCESS';
export const FETCH_RANDOM_PHOTOS_FAILED = 'FETCH_RANDOM_PHOTOS_FAILED';
